FROM python:3.11.2

RUN pip install pyspark kafka-python

RUN apt-get update && apt-get install -y \
 default-jdk 

ENV JAVA_HOME /usr/lib/jvm/java-1.11.0-openjdk-arm64

ENV KAFKA_BOOTSTRAP_SERVERS host.docker.internal:9092
ENV SPARK_MASTER spark://host.docker.internal:7077

COPY /code .

COPY entrypoint.sh /usr/local/bin/ 
RUN chmod 755 /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]
