FROM python:3.10.2

RUN pip install pyspark

RUN apt-get update && apt-get install -y \
 default-jdk 

ENV JAVA_HOME /usr/lib/jvm/java-1.11.0-openjdk-arm64

COPY kafka_consumer.py .

CMD ["python", "kafka_consumer.py"]
