kind: Deployment
apiVersion: apps/v1
metadata:
  name: spark-worker-k8s
  namespace: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-worker-k8s
  template:
    metadata:
      namespace: spark
      labels:
        component: spark-worker-k8s
    spec:
      containers:
        - name: spark-worker-k8s
          image: spark
          env:
            - name: SPARK_MASTER_HOST
              value: "spark-master-k8s"
            - name: SPARK_WORKER_PORT
              value: "7078"
            - name: SPARK_WORKER_MEMORY
              value: "4g"
          imagePullPolicy: Never
          args: ["worker"]
          ports:
            - containerPort: 8091
            - containerPort: 7078
          resources:
            requests:
              cpu: 100m
              memory: 5Gi
          volumeMounts:
            - mountPath: /data
              name: spark-data

      volumes:
        - name: spark-data
          persistentVolumeClaim:
            claimName: spark-persistent-volume-claim

---
kind: Service
apiVersion: v1
metadata:
  name: spark-worker-k8s
  namespace: spark
spec:
  ports:
    - name: webui
      port: 8091
      targetPort: 8091
    - name: spark
      port: 7078
      targetPort: 7078
  selector:
    component: spark-worker-k8s
---
kind: Service
apiVersion: v1
metadata:
  name: spark-worker-k8s
  namespace: test
spec:
  type: ExternalName
  externalName: spark-worker-k8s.spark.svc.cluster.local 
  ports:
    - name: spark
      port: 7078
      targetPort: 7078
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-spark-worker
  namespace: spark
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "local-spark-worker"
    http:
      paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: spark-worker-k8s
              port:
                number: 8091