# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: spark-local-storage
#   namespace: spark
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: spark-persistent-volume
#   namespace: spark
# spec:
#   capacity:
#     storage: 10Gi
#   volumeMode: Filesystem
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Delete
#   storageClassName: spark-local-storage
#   local:
#     path: /var/tmp/test
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: spark-persistent-volume-claim
#   namespace: spark
# spec:
#   accessModes:
#     - ReadWriteOnce
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 10Gi
#   storageClassName: spark-local-storage
# ---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: spark-persistent-volume
  namespace: spark
  labels:
    name: spark-persistent-volume
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: spark-persistent-volume
    fsType: ext4
    readOnly: true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spark-persistent-volume-claim
  namespace: spark
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: spark-persistent-volume
